# backend/gemini_report.py
import google.generativeai as genai
import os

async def generate_diagnostic_report(prediction_result: str, confidence: float, all_probabilities: dict):
    """
    Generates a patient-friendly diagnostic-style report using Gemini AI.

    Args:
        prediction_result (str): The predicted tumor class name.
        confidence (float): The confidence percentage of the prediction.
        all_probabilities (dict): A dictionary of all class names and their probabilities.

    Returns:
        str: The AI-generated diagnostic report text.
    """
    # Configure Gemini API key from environment variable
    # IMPORTANT: Never hardcode your API key directly in code for production.
    # Use environment variables for security.
    api_key = os.getenv("GOOGLE_API_KEY")
    if not api_key:
        print("GOOGLE_API_KEY environment variable not set. Gemini report generation will fail.")
        return "Error: Gemini API key not configured. Cannot generate diagnostic report."
    
    genai.configure(api_key=api_key)

    try:
        # --- CORRECTED LINE ---
        # Using 'gemini-1.5-flash-latest' as it's generally more stable and widely available
        model = genai.GenerativeModel('gemini-1.5-flash-latest') 

        # Construct a clear and constrained prompt for Gemini
        prompt = f"""
        You are an AI assistant tasked with generating a patient-friendly, preliminary diagnostic summary for a brain MRI scan based solely on a deep learning model's classification.

        **Crucial Guidelines:**
        1.  **DO NOT provide any medical advice, diagnosis, or treatment recommendations.**
        2.  **Explicitly state that this is an AI-generated preliminary report and NOT a substitute for professional medical evaluation.**
        3.  Maintain a neutral, informative, and empathetic tone.
        4.  Keep the report concise and easy for a layperson to understand.
        5.  Avoid overly technical medical jargon.

        **Model Prediction Data:**
        -   Predicted Class: {prediction_result}
        -   Confidence Level: {confidence:.2f}%
        -   Probabilities for all classes: {all_probabilities}

        **Please generate the report, ensuring it includes:**
        -   A clear disclaimer that this is an AI-generated, preliminary analysis.
        -   The primary finding (predicted tumor class).
        -   The confidence level for the prediction.
        -   A strong recommendation to consult a qualified healthcare professional for a definitive diagnosis and treatment plan.

        **Example output structure:**
        "Preliminary AI Analysis of Brain MRI Scan

        This report is generated by an artificial intelligence model and is for informational purposes only. It is not a medical diagnosis and should not be used to guide treatment decisions. Always consult with a qualified healthcare professional for any medical concerns.

        **Key Finding:**
        The AI model has identified a potential presence of [Predicted Class, e.g., 'glioma_tumor'] with a confidence level of [Confidence]%.

        **Important Note:**
        AI model predictions require professional medical review. A definitive diagnosis can only be made by a licensed physician after comprehensive clinical evaluation, including additional tests and imaging as needed. This AI analysis is intended to assist, not replace, medical expertise."
        """
        
        # Generate content with Gemini
        response = model.generate_content(prompt)
        
        # Access the text from the response object
        return response.text

    except Exception as e:
        print(f"Error generating Gemini report: {e}")
        # Return a user-friendly error message if Gemini fails
        return "A diagnostic report could not be generated at this time. Please consult a healthcare professional for interpretation of your MRI results."